### ISSUE TITLE
Doesn't recognise browsers

### ISSUE THREAD

**Issue by dhruvdutt** [gokulkrishh/set-default-browser#1]
`set-default-browser chrome`
`set-default-browser google-chrome`
`set-default-browser firefox`

None of them worked. `Browser not found 🙀`

**Comment by gokulkrishh** [comment]
@dhruvdutt Which OS you are using ?? Its working for me. I am using OSX.
<img width="944" alt="screen shot 2017-06-08 at 10 53 35 am" src="https://user-images.githubusercontent.com/2944237/26913499-d38933a2-4c38-11e7-8d01-9bbedc848205.png">

**Comment by dhruvdutt** [comment]
Kubuntu 17.04 x64, KDE 5.10.0
Kernel Version: 4.10.0-22-generic

**Comment by gokulkrishh** [comment]
@dhruvdutt I see. As of now `set-default-browser` is supported only in `OSX`. It is also mentioned in README.

**Comment by gokulkrishh** [comment]
Closing this issue as of now. This module is only supported in OSX.
