### ISSUE TITLE
Add support for FirefoxDeveloperEdition

### ISSUE THREAD

**Issue by cRAN-cg** [gokulkrishh/set-default-browser#2]
Thank you for making this module which made life more easier but I use FirefoxDeveloperEdition for my work and have made some changes to your code locally provides support to the it. Can I make a PR for the same.

**Comment by gokulkrishh** [comment]
@cRAN-cg Glad to know. Yes that would be great 👍 .

**Comment by nashashibi** [comment]
Thanks for this, it's very helpful!

Is **Firefox Developer Edition** supported now? If yes, what's the command line?

**Comment by cRAN-cg** [comment]
firefoxDE is the arg you would like to passin

**Comment by gokulkrishh** [comment]
@cRAN-cg Sure!

**Comment by gokulkrishh** [comment]
Closing in favour of #3
